name: Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Build and push multi-arch Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/hezzitlda/cftl:buildcache
          cache-to: type=registry,ref=ghcr.io/hezzitlda/cftl:buildcache,mode=max
          tags: |
            ghcr.io/hezzitlda/cftl:${{ env.VERSION }}
            ghcr.io/hezzitlda/cftl:latest
